### ISSUE TITLE
Array and map environment variables

### ISSUE THREAD

**Issue by akrantz01** [WaffleHacks/wafflemaker#11]
This would make it easier to represent maps and arrays in environment variables by allowing native TOML maps and arrays that get serialized to JSON when set in the container's environment. This should also work for secrets loaded from Vault.

Instead of
```toml
[environment]
  map = '{"key":"value","data":1}'
  array = '["e1", "e2", "e3"]'
```
you would be able to do
```toml
[environment]
  map = { key = "value", data = 1 }
  array = [ "e1", "e2", "e3" ]
```
